version: "2"

services:
  ckan:
    build: .
    volumes:
      - ./production.ini:/etc/ckan/default/production.ini
      - ./jetty8:/etc/default/jetty8
      - ./start_up.sh:/start_up.sh
      - ./ckan_config:/etc/ckan
      - ./ckanext-customschema:/usr/lib/ckan/default/src/ckanext-customschema
      # uncomment to use local mapped vol for dev
      #- ./ckanext-landdbcustomize:/usr/lib/ckan/default/src/ckanext-landdbcustomize
      - ./ckan_storage:/var/lib/ckan
    ports:
      - "80:80"
      - "443:443"
      - "8800:8800"
    env_file: .env
    command: ./start_up.sh
  postgres:
    image: postgres:9.5
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file: .env
  redis:
    image: redis:4.0
    volumes:
      - ./redis_data:/data
